using System.Diagnostics.Metrics;

namespace Lab10
{
    public partial class fMain : Form
    {
        public fMain()
        {
            InitializeComponent();
        }

        private void fMain_Resize(object sender, EventArgs e)
        {
            int buttonSize = 5 * btnAdd.Width + 2 * tsSeparator1.Width + 30;
            btnExit.Margin = new Padding(Width - buttonSize, 0, 0, 0);
        }

        private void gvTowns_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {

        }

        private void fMain_Load(object sender, EventArgs e)
        {
            // Ensure columns are not autogenerated by the DataGridView
            gvStudents.AutoGenerateColumns = false;

            // Create and add columns to the DataGridView
            DataGridViewColumn column;

            column = new DataGridViewTextBoxColumn();
            column.DataPropertyName = "Fullname";
            column.Name = "ПІБ";
            gvStudents.Columns.Add(column);

            column = new DataGridViewTextBoxColumn();
            column.DataPropertyName = "Age";
            column.Name = "Вік";
            column.Width = 60;
            gvStudents.Columns.Add(column);

            column = new DataGridViewTextBoxColumn();
            column.DataPropertyName = "University";
            column.Name = "Університет";
            gvStudents.Columns.Add(column);

            column = new DataGridViewTextBoxColumn();
            column.DataPropertyName = "Specialty";
            column.Name = "Спеціальність";
            gvStudents.Columns.Add(column);

            column = new DataGridViewTextBoxColumn();
            column.DataPropertyName = "Course";
            column.Name = "К-ть дисциплін";
            column.Width = 60;
            gvStudents.Columns.Add(column);

            column = new DataGridViewCheckBoxColumn();
            column.DataPropertyName = "Livedorm";
            column.Name = "Гуртожиток";
            column.Width = 95;
            gvStudents.Columns.Add(column);

            column = new DataGridViewCheckBoxColumn();
            column.DataPropertyName = "PaidFree";
            column.Name = "Бюджет";
            column.Width = 90;
            gvStudents.Columns.Add(column);

            column = new DataGridViewCheckBoxColumn();
            column.DataPropertyName = "Contract";
            column.Name = "Контракт";
            column.Width = 90;
            gvStudents.Columns.Add(column);

            column = new DataGridViewTextBoxColumn();
            column.DataPropertyName = "AverageGrade";
            column.Name = "Середня оцінка";
            column.Width = 80;
            gvStudents.Columns.Add(column);

            // Bind a sample town data to the BindingSource
            bindSrcStud.Add(new Student("Студент1", 18, "УМСФ", "ІПЗ", 5, false, true, false,5));

            // Trigger the resize event to adjust the layout if necessary
            EventArgs args = new EventArgs();
            OnResize(args);

        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            Student student = new Student();

            fStudent fs = new fStudent(ref student);
            if (fs.ShowDialog() == DialogResult.OK)
            {
                bindSrcStud.Add(student);
            }
        }

        private void btnEdit_Click(object sender, EventArgs e)
        {
            Student student = (Student)bindSrcStud.List[bindSrcStud.Position];

            fStudent fs = new fStudent(ref student);
            if (fs.ShowDialog() == DialogResult.OK)
            {
                bindSrcStud.List[bindSrcStud.Position] = student;
            }
        }

        private void btnDel_Click(object sender, EventArgs e)
        {
            if (MessageBox.Show("Видалити поточний запис ?", "Видалення запису",
                MessageBoxButtons.OKCancel, MessageBoxIcon.Warning) == DialogResult.OK)
            {
                bindSrcStud.RemoveCurrent();
            }
        }

        private void btnClear_Click(object sender, EventArgs e)
        {
            if (MessageBox.Show("Очистити таблицю?\n\nВсі дані будуть втрачені", "Очищення даних",
                MessageBoxButtons.OKCancel, MessageBoxIcon.Question) == DialogResult.OK)
            {
                bindSrcStud.Clear();
            }
        }

        private void btnExit_Click(object sender, EventArgs e)
        {
            if (MessageBox.Show("Закрити застосунок?", "Вихід з програми",
                MessageBoxButtons.OKCancel, MessageBoxIcon.Question) == DialogResult.OK)
            {
                Application.Exit();
            }
        }
    }
}
