using System.Diagnostics.Metrics;

namespace Lab10
{
    public partial class fMain : Form
    {
        public fMain()
        {
            InitializeComponent();
        }

        private void fMain_Resize(object sender, EventArgs e)
        {
            int buttonSize = 5 * btnAdd.Width + 2 * tsSeparator1.Width + 30;
            btnExit.Margin = new Padding(Width - buttonSize, 0, 0, 0);
        }

        private void gvTowns_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {

        }

        private void fMain_Load(object sender, EventArgs e)
        {
            // Ensure columns are not autogenerated by the DataGridView
            gvTowns.AutoGenerateColumns = false;

            // Create and add columns to the DataGridView
            DataGridViewColumn column;

            column = new DataGridViewTextBoxColumn();
            column.DataPropertyName = "Fullname";
            column.Name = "ПІБ";
            gvTowns.Columns.Add(column);

            column = new DataGridViewTextBoxColumn();
            column.DataPropertyName = "Age";
            column.Name = "Вік";
            column.Width = 60;
            gvTowns.Columns.Add(column);

            column = new DataGridViewTextBoxColumn();
            column.DataPropertyName = "University";
            column.Name = "Університет";
            gvTowns.Columns.Add(column);

            column = new DataGridViewTextBoxColumn();
            column.DataPropertyName = "Specialty";
            column.Name = "Спеціальність";
            gvTowns.Columns.Add(column);

            column = new DataGridViewTextBoxColumn();
            column.DataPropertyName = "Course";
            column.Name = "К-ть дисциплін";
            column.Width = 60;
            gvTowns.Columns.Add(column);

            /*column = new DataGridViewTextBoxColumn();
            column.DataPropertyName = "AverageGrade";
            column.Name = "Середня оцінка";
            column.Width = 80;
            gvTowns.Columns.Add(column);*/

            column = new DataGridViewCheckBoxColumn();
            column.DataPropertyName = "Livedorm";
            column.Name = "Гуртожиток";
            column.Width = 95;
            gvTowns.Columns.Add(column);

            column = new DataGridViewCheckBoxColumn();
            column.DataPropertyName = "PaidFree";
            column.Name = "Бюджет";
            column.Width = 90;
            gvTowns.Columns.Add(column);

            column = new DataGridViewCheckBoxColumn();
            column.DataPropertyName = "Contract";
            column.Name = "Контракт";
            column.Width = 90;
            gvTowns.Columns.Add(column);

            // Bind a sample town data to the BindingSource
            bindSrcTowns.Add(new Student("Студент1", 18, "УМСФ", "ІПЗ", 5, 4, false, true, false));

            // Trigger the resize event to adjust the layout if necessary
            EventArgs args = new EventArgs();
            OnResize(args);

        }
    }
}
